name: Test exiting on failure

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Try to fail
      run: exit 0
    - name: Print message if we don't fail
      run: echo Should not get here
