name: Test exiting on failure

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: First step
      run: |
        echo FIRST OK
    - name: Try to fail
      run: |
        echo YES
        echo YES
        echo NOW FAILING
        exit 1
    - name: Next step
      run: |
        echo NEXT STEP AFTER FAIL
    - name: Cleanup
      if: ${{ always() }}
      run: echo RUNNING CLEANUP!

